In [1]:
import math
import torch
from torch import nn
from tqdm.notebook import tqdm
from torch_toys.data_gen import MNKTicTacToe


## Configurations
BOARD_WIDTH=15
BOARD_HEIGHT=15
WIN_LENGTH=5
FREQ = 8
NUM_STEPS = 10000


gen = MNKTicTacToe(BOARD_HEIGHT, BOARD_WIDTH, WIN_LENGTH)

In [21]:
def generate_batch(batchsz: int):
    global gen
    boards = []
    winners = []
    nexts = []
    for i in range(batchsz):
        s = gen.generate()
        boards.append(gen.board_to_tensor(s).unsqueeze(0))
        nexts.append(gen.next_to_tensor(s))
        winners.append(gen.winner_to_tensor(s))
    
    boards = torch.cat(boards, 0)
    winners = torch.cat(winners, 0)
    nexts = torch.cat(nexts, 0)
    return boards, winners, nexts


def generate_pos_encode(d:int)->torch.Tensor:
    global gen
    pos_r, pos_c = gen.board_pos_to_tensor()
    res = []
    for freq in range(d):
        w = (freq + 1) * math.pi
        res.append(torch.cos(pos_r * w).unsqueeze(0))
        res.append(torch.cos(pos_c * w).unsqueeze(0))
        res.append(torch.sin(pos_r * w).unsqueeze(0))
        res.append(torch.sin(pos_c * w).unsqueeze(0))
    return torch.cat(res, 0).unsqueeze(0)

class TicTacToeNet(nn.Module):
    def __init__(self, dim_embed:int, num_heads:int=8, num_layers:int=3, use_dropout:bool=False, use_stochastic_depth:bool=False):
        super().__init__()
        self.dim_embed = dim_embed
        self.num_heads = num_heads
        self.num_layers = num_layers
        self.use_dropout = use_dropout
        self.use_stochastic_depth = use_stochastic_depth

        self.token_embed = nn.Embedding(2, dim_embed)
        self.mark_embed = nn.Embedding(3, dim_embed)
        self.lst_msa = nn.ModuleList()

        for _ in range(self.num_layers):
            self.lst_msa.append(nn.MultiheadAttention(self.dim_embed, self.num_heads,use_dropout)




    net = 
pos_enc = generate_pos_encode(FREQ)

In [8]:
for stepidx in range(NUM_STEPS):

    generate_batch(10)

(tensor([[0, 0, 0,  ..., 2, 2, 0],
         [0, 1, 0,  ..., 0, 2, 0],
         [1, 1, 0,  ..., 2, 0, 0],
         ...,
         [0, 1, 0,  ..., 1, 0, 1],
         [0, 1, 0,  ..., 0, 0, 0],
         [0, 2, 0,  ..., 0, 0, 0]]),
 tensor([0, 1, 2, 0, 0, 0, 1, 1, 1, 0]),
 tensor([1, 2, 1, 2, 2, 2, 2, 2, 2, 2]))